stages:
  - test
  - deploy

test:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v2
  script:
    - mkdir _build && cd _build
    - ../autogen.sh
    - make
    - make install
    - make distcheck
    - cd ..
    - python2 -m flake8 .
    - mkdir public
    - cd public
    - yelp-build html ../doc/C/index.docbook
  artifacts:
    paths:
      - public


ubuntu-19.04-glib:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v2
  script:
    - ./autogen.sh
    - make
    - make install
    - export PATH=$HOME/.local/bin:$PATH
    - mkdir -p $HOME/.config
    - echo "use_local_modulesets = True" >> $HOME/.config/jhbuildrc
    - sudo apt-file update
    - jhbuild --no-interact --exit-on-error sysdeps --install --assume-yes glib
    - sudo apt install -y zlib1g-dev docbook-xml docbook-xsl
    - jhbuild --no-interact --exit-on-error build glib

pages:
  image: alpine:latest
  stage: deploy
  needs: ["test"]
  script:
   - echo
  artifacts:
    paths:
      - public
  only:
    - master
