stages:
  - test
  - deploy

documentation:
  image: docker.io/sphinxdoc/sphinx
  script:
    - python3 -m pip install sphinx_rtd_theme sphinx-lint
    - sphinx-build --keep-going -W ./doc ./html ./doc/*.rst
    - |
      for dir in ./doc/po/*/; do
        lang="$(basename "$dir")"
        sphinx-build -Dlanguage="$lang" --keep-going ./doc ./html/"$lang" ./doc/*.rst
        sphinx-lint $dir/LC_MESSAGES/docs.po
      done
  artifacts:
    paths:
      - html

test-py3:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v5
  script:
    # verify modulesets
    - xmllint --noout modulesets/*.{xml,xsl,modules}
    # autotools install
    - mkdir _build && cd _build
    - ../autogen.sh --with-python=python3
    - make
    - make install
    - make distcheck
    - cd ..
    # simple install
    - ./autogen.sh --simple-install --with-python=python3
    - make install
    - $HOME/.local/bin/jhbuild help
    # flake 8
    - python3 -m flake8 .

ub20.04-py3-glib:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v5
  before_script:
    # Update for root cert updates
    - sudo apt-get update
    - sudo apt-get upgrade -y
  script:
    - ./autogen.sh --with-python=python3
    - make
    - make install
    - export PATH=$HOME/.local/bin:$PATH
    - mkdir -p $HOME/.config
    - echo "use_local_modulesets = True" >> $HOME/.config/jhbuildrc
    - sudo apt-file update
    - jhbuild help
    - jhbuild --no-interact --exit-on-error sysdeps --install --assume-yes glib
    - sudo apt install -y docbook-xml docbook-xsl
    - jhbuild --no-interact --exit-on-error build glib

pages:
  image: alpine:latest
  stage: deploy
  needs: ["documentation"]
  script:
   - echo
  artifacts:
    paths:
      - html
  publish: html
  only:
    - master
