stages:
  - test
  - deploy

test-py3:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v5
  script:
    # autotools install
    - mkdir _build && cd _build
    - ../autogen.sh --with-python=python3
    - make
    - make install
    - make distcheck
    - cd ..
    # simple install
    - ./autogen.sh --simple-install --with-python=python3
    - make install
    - $HOME/.local/bin/jhbuild help
    # flake 8
    - python3 -m flake8 .
    # docs
    - mkdir public
    - cd public
    - yelp-build html ../doc/C/index.docbook
  artifacts:
    paths:
      - public

ub20.04-py3-glib:
  image: registry.gitlab.gnome.org/gnome/jhbuild/jhbuild:v5
  script:
    - ./autogen.sh --with-python=python3
    - make
    - make install
    - export PATH=$HOME/.local/bin:$PATH
    - mkdir -p $HOME/.config
    - echo "use_local_modulesets = True" >> $HOME/.config/jhbuildrc
    - sudo apt-file update
    - jhbuild help
    - jhbuild --no-interact --exit-on-error sysdeps --install --assume-yes glib
    - sudo apt install -y docbook-xml docbook-xsl
    - jhbuild --no-interact --exit-on-error build glib

pages:
  image: alpine:latest
  stage: deploy
  needs: ["test-py3"]
  script:
   - echo
  artifacts:
    paths:
      - public
  only:
    - master
