[build-system]
requires = ["meson-python"]
build-backend = "mesonpy"

[project]
name = "jhbuild"
version = "0"
readme = "README.rst"
license = {file = "COPYING"}

[project.scripts]
jhbuild = "jhbuild:main.main"
