FROM ubuntu:disco

RUN apt update && apt install -y \
    autoconf \
    automake \
    autopoint \
    gettext \
    git \
    libtool \
    make \
    patch \
    pkg-config \
    python \
    trang \
    yelp-tools

ENV LANG C.UTF-8