MODIR=../mo

%.mo: %.po
	msgfmt -o $@ $<
	@mkdir -p $(MODIR)/$(strip $(basename $@ .mo))/LC_MESSAGES
	@mv $@ $(MODIR)/$(strip $(basename $@ .mo))/LC_MESSAGES/jhbuild.mo 

LANGUAGES=$(shell grep -v '^\#' LINGUAS)

install: $(LANGUAGES:=.mo)
